### ISSUE TITLE
How should we share maintenance?

### ISSUE THREAD

**Issue by azriel91** [amethyst/shred#173]
Hiya all, since `shred`, `shrev`, `specs` (some more?) moved from `slide-rs`, I'm not sure who should be reviewing / approving / merging pull requests, and releasing / publishing (who has permissions?).

My thoughts on issues / code are mostly aligned with `amethyst` (design decisions, review requirements, testing, style). Releasing / publishing *may* be on-demand given there is sufficient test coverage / automated guards if something is inconsistent.

**Comment by WaDelma** [comment]
I am currently quite busy, so not sure how much I can contribute this year.

**Comment by azriel91** [comment]
Would you and @torkleyy be fine with `amethyst/amethyst` maintainers managing this? Am certain there's enough experience that quality is maintained.

For `shred` at least, it's relatively stable so it would mainly be maintenance mode rather than feature development. I'd like to get the relevant in-progress PRs merged / published
(https://github.com/amethyst/shred/pull/163, https://github.com/amethyst/shred/pull/172, dependency updates)

@torkleyy: would need crates.io [owner permissions](https://crates.io/crates/shred).

**Comment by azriel91** [comment]
Received permissions from `@torkleyy`, and would take that as a sign of a go ahead.
Shall do some publishing now (let me know if/when I'm over-eager in executing actions).
