### ISSUE TITLE
Lifetime Parameters

### ISSUE THREAD

**Issue by matt328** [amethyst/shred#233]
It's probably just because I'm new to rust, but how do I make a `Dispatcher` a member of a struct without having to bubble lifetime parameters through my entire object hierarchy?

**Comment by Imberflur** [comment]
I think you should be able to set the lifetime parameters to `'static` as long as all your systems are `'static` (i.e. none of your system types contain lifetime parameters themselves).

**Comment by matt328** [comment]
This is what I ended up doing.  It felt kinda of wrong, but these things should live for the entire lifetime of the program, and I think that's basically the definition of `'static`.
