### ISSUE TITLE
Allow runtime `SystemData`

### ISSUE THREAD

**Issue by torkleyy** [amethyst/shred#79]
`SystemData` currently has associated functions for `read` and `write`. This prohibits creating more dynamic systems that don't specify what they fetch at compile-time.

## Proposal

* add `SystemData::Specifier`
* move `SystemData::read` and `SystemData::write` to `Specifier` and let them take `&self`
* add a `specifier` method to `System` with a default implementation that works for all current cases

## Example

This is what a custom implementation could look like (very primitive).

```rust
struct CustomData {
    // ..
}

impl<'a> SystemData<'a> for CustomData {
    type Specifier = CustomSpec;

    fn fetch(spec: &Self::Specifier, res: &'a Resources) -> Self {
        unimplemented!()
    }
}

struct CustomSpec {
    reads: Vec<ResourceId>,
    writes: Vec<ResourceId>,
}

impl Specifier for CustomSpec {
    fn reads(&self) -> Vec<ResourceId> {
        self.reads.clone()
    }

    fn writes(&self) -> Vec<ResourceId> {
        self.writes.clone()
    }
}
```

## Possible complications

The default implementation for `System::specifier` won't be able to use the usual `Specifier::default` function as you'd expect, because we can't specialize the default for that method for `Specifier: Default`.

## Unresolved questions

* Find a better name for `Specifier`

---

Name suggestions for `Specifier` welcome!

**Comment by torkleyy** [comment]
cc @Aceeri @Xaeroxe @jojolepro

**Comment by WaDelma** [comment]
Only thing that comes mind is `AccessConstraints` which seems awfully generic.

**Comment by tversteeg** [comment]
How about `ResourceIdAccessor`?

**Comment by torkleyy** [comment]
Ah, I think `Accessor` is good! No need to prepend `ResourceId`.
